version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=clinica_db
    depends_on:
      - db 
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: clinica_db 
    ports:
      - "33066:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: