version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: