# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vehiculos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vehiculos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvehiculos.proto\x12\x08vehiculo\"&\n\x0fVehiculoRequest\x12\x13\n\x0bvehiculo_id\x18\x01 \x01(\t\"C\n\x16\x44isponibilidadResponse\x12\x12\n\ndisponible\x18\x01 \x01(\x08\x12\x15\n\restado_actual\x18\x02 \x01(\t2i\n\x0fVehiculoService\x12V\n\x17VerificarDisponibilidad\x12\x19.vehiculo.VehiculoRequest\x1a .vehiculo.DisponibilidadResponseB\x1dZ\x1bvehiculos-service-go/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehiculos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033vehiculos-service-go/protos'
  _globals['_VEHICULOREQUEST']._serialized_start=29
  _globals['_VEHICULOREQUEST']._serialized_end=67
  _globals['_DISPONIBILIDADRESPONSE']._serialized_start=69
  _globals['_DISPONIBILIDADRESPONSE']._serialized_end=136
  _globals['_VEHICULOSERVICE']._serialized_start=138
  _globals['_VEHICULOSERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
