// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.0
// source: protos/vehiculos.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VehiculoServiceClient is the client API for VehiculoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VehiculoServiceClient interface {
	// Un método para verificar la disponibilidad de un vehículo.
	VerificarDisponibilidad(ctx context.Context, in *VehiculoRequest, opts ...grpc.CallOption) (*DisponibilidadResponse, error)
}

type vehiculoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVehiculoServiceClient(cc grpc.ClientConnInterface) VehiculoServiceClient {
	return &vehiculoServiceClient{cc}
}

func (c *vehiculoServiceClient) VerificarDisponibilidad(ctx context.Context, in *VehiculoRequest, opts ...grpc.CallOption) (*DisponibilidadResponse, error) {
	out := new(DisponibilidadResponse)
	err := c.cc.Invoke(ctx, "/vehiculo.VehiculoService/VerificarDisponibilidad", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VehiculoServiceServer is the server API for VehiculoService service.
// All implementations must embed UnimplementedVehiculoServiceServer
// for forward compatibility
type VehiculoServiceServer interface {
	// Un método para verificar la disponibilidad de un vehículo.
	VerificarDisponibilidad(context.Context, *VehiculoRequest) (*DisponibilidadResponse, error)
	mustEmbedUnimplementedVehiculoServiceServer()
}

// UnimplementedVehiculoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVehiculoServiceServer struct {
}

func (UnimplementedVehiculoServiceServer) VerificarDisponibilidad(context.Context, *VehiculoRequest) (*DisponibilidadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificarDisponibilidad not implemented")
}
func (UnimplementedVehiculoServiceServer) mustEmbedUnimplementedVehiculoServiceServer() {}

// UnsafeVehiculoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehiculoServiceServer will
// result in compilation errors.
type UnsafeVehiculoServiceServer interface {
	mustEmbedUnimplementedVehiculoServiceServer()
}

func RegisterVehiculoServiceServer(s grpc.ServiceRegistrar, srv VehiculoServiceServer) {
	s.RegisterService(&VehiculoService_ServiceDesc, srv)
}

func _VehiculoService_VerificarDisponibilidad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehiculoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiculoServiceServer).VerificarDisponibilidad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vehiculo.VehiculoService/VerificarDisponibilidad",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiculoServiceServer).VerificarDisponibilidad(ctx, req.(*VehiculoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VehiculoService_ServiceDesc is the grpc.ServiceDesc for VehiculoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehiculoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vehiculo.VehiculoService",
	HandlerType: (*VehiculoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerificarDisponibilidad",
			Handler:    _VehiculoService_VerificarDisponibilidad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/vehiculos.proto",
}
